import data from './content.json';
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base=import.meta.env.BASE_URL;
const asset=s=>base+'assets/'+s;
const titles=['Bienvenue','Mode d’emploi','Objectifs','Concepts essentiels','La méthode LN-IA','Votre atelier VS Code','Exercices guidés','Questions de réflexion','Après la séance','Auto-évaluation','Modèles à compléter','Pour continuer'];
const fileNames=['fiche-depart-candidat.md','objectif-personnel-challenge.md','liste-premiers-livrables.md'];
const promptNames=['Clarifier mon objectif','Transformer mon idée en objectif','Clarifier mon intention','Rendre mon objectif mesurable','Créer mon premier README'];
const posters=[['ordre-du-jour.png','Ordre du jour'],['ouverture.png','La séance d’ouverture'],['deux-axes.png','Deux axes pour démarrer'],['deroulement.png','Déroulement de la séance'],['message-methode.png','Le message LN-IA']];
let state={view:'lesson',section:0,slide:0};
let saved={};try{saved=JSON.parse(localStorage.getItem('lnia-s01-v1')||'{}')}catch{}
const persist=()=>{try{localStorage.setItem('lnia-s01-v1',JSON.stringify(saved))}catch{notify('La sauvegarde locale est indisponible. Exportez votre travail.')}};
function notify(t){let n=document.getElementById('status');n.textContent=t;clearTimeout(notify.timer);notify.timer=setTimeout(()=>n.textContent='',4500)}
function download(text,name,type='text/markdown;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function copy(text,btn){try{await navigator.clipboard.writeText(text);btn.textContent='Copié !';setTimeout(()=>btn.textContent='Copier',1800);notify('Texte copié. Collez-le avec Ctrl+V.')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.append(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();if(ok)notify('Texte copié.');else{notify('Sélectionnez le texte puis utilisez Ctrl+C.');btn.closest('.copyblock')?.querySelector('pre')?.focus()}}}
const blocks=[];
function copyBlock(text,label='Texte à copier',name='prompt.md'){let id=blocks.push(text)-1;return `<div class="copyblock"><div class="copyhead"><span>${e(label)}</span><div><button data-copy="${id}">Copier</button><button data-download="${id}" data-name="${name}" aria-label="Télécharger ${e(label)}">Télécharger .md</button></div></div><pre tabindex="0">${e(text)}</pre></div>`}
function shell(){document.getElementById('app').innerHTML=`<aside class="sidebar"><a class="brand" href="#lesson/0" aria-label="LN-IA Accueil"><img src="${asset('logo-ln-ia.png')}" alt="LN-IA"></a><div class="side-label">CHALLENGE 100 JOURS</div><p class="side-title">Votre première<br>production commence ici.</p><div class="session-tag">MODULE 01 <span>•</span> SÉANCE 01</div><nav aria-label="Parcours de la leçon" id="sectionnav">${titles.map((t,i)=>`<a href="#lesson/${i}" data-section="${i}"><span>${String(i).padStart(2,'0')}</span>${t}</a>`).join('')}</nav><div class="side-bottom"><span class="gold">RELANCE AUTOMNE 2026</span><p>Prof. Abderrahman EL HISSE</p><small>Apprendre en produisant.</small></div></aside><div class="workspace"><header class="topbar"><button id="menu" aria-label="Afficher le parcours" aria-expanded="false">☰</button><span class="toplabel">25 SEPTEMBRE 2026 <span> / </span> LN-IA</span><nav aria-label="Modes d’affichage" class="view-tabs"><a href="#lesson/0" data-view="lesson">Leçon</a><a href="#slides/0" data-view="slides">Présenter</a><a href="#prompts" data-view="prompts">Prompts</a><a href="#posters" data-view="posters">Affiches</a></nav><button id="fullscreen" title="Plein écran">Plein écran</button></header><main id="main" tabindex="-1"></main><footer class="footer">L’IA propose. L’humain contrôle. L’atelier organise. Le livrable prouve.</footer></div><div id="status" role="status" aria-live="polite"></div><dialog id="lightbox"><button id="closebox" aria-label="Fermer l’affiche">Fermer ×</button><img alt=""></dialog>`;
document.getElementById('menu').onclick=()=>{let on=document.body.classList.toggle('menu-open');document.getElementById('menu').setAttribute('aria-expanded',on)};
document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{notify('Utilisez F11 pour le plein écran.')}};
document.getElementById('closebox').onclick=()=>document.getElementById('lightbox').close();}
function intro(){return `<section class="welcome"><p class="eyebrow">SÉANCE 01 · LANCEMENT, DÉCOUVERTE ET CADRAGE</p><h1>Passer de l’intention<br>à la <em>première preuve.</em></h1><p class="lead">Ouvrez votre atelier numérique. Clarifiez ce que vous voulez produire avec l’IA. Repartez avec un premier fichier relu, daté et classé.</p><div class="meta"><span>Vendredi 25 septembre 2026</span><span>19 h · Heure du Maroc</span><span>90 à 120 min</span></div><div class="welcome-actions"><a class="primary" href="#lesson/1">Commencer la leçon <span>→</span></a><a class="secondary" href="#slides/0">Lancer la présentation</a></div><div class="first-proof"><span class="proof-index">01</span><div><span class="eyebrow">LE LIVRABLE DE CETTE SÉANCE</span><h2>fiche-depart-candidat.md</h2><p>Votre activité, votre objectif et une preuve utile à produire.</p></div><span class="proof-mark" aria-hidden="true">✓</span></div><div class="two-axes"><article><span class="step-label">AXE 01 / L’OUTIL</span><h2>VS Code simplement</h2><p>Créer un dossier, ouvrir un fichier, écrire et enregistrer.</p></article><article><span class="step-label">AXE 02 / LA MÉTHODE</span><h2>LAB-NUMÉRIQUE-IA</h2><p>Définir une intention, contrôler la production et conserver une preuve.</p></article></div></section>`}
const checkItems=["J’ai ouvert VS Code au moins une fois.","J’ai créé mon dossier de travail.","J’ai complété fiche-depart-candidat.md.","J’ai rédigé mon intention personnelle.","J’ai identifié trois livrables souhaités.","Je sais où ranger mes preuves."];
function checks(){return `<div class="checklist"><h3>Checklist avant la séance 02</h3><p>Cochez les actions réalisées. Votre suivi reste dans ce navigateur.</p>${checkItems.map((s,i)=>`<label><input type="checkbox" data-save="check-${i}" ${saved['check-'+i]?'checked':''}>${s}</label>`).join('')}</div>`}
function table(rows){return `<div class="table-scroll"><table><thead><tr>${rows[0].map(c=>`<th scope="col">${e(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(r=>`<tr>${r.map(c=>`<td>${e(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function reflection(){const qs=data.sections[6].items.filter(x=>x.type==='p'&&x.text.startsWith('Question'));return `<p class="lead">Prenez quelques minutes pour répondre avec vos propres mots.</p><div class="form-section">${qs.map((q,i)=>`<label for="ref-${i}">${e(q.text)}</label><textarea id="ref-${i}" data-save="ref-${i}" rows="3" placeholder="Votre réponse…">${e(saved['ref-'+i]||'')}</textarea>`).join('')}</div>${exportButton()}`}
function exportButton(){return `<div class="export"><button class="primary" data-export>Exporter mon travail .md</button><p>Vos réponses restent sur cet appareil. Téléchargez-les pour les conserver ou les partager.</p></div>`}
function assessment(){const rows=data.sections[8].items.find(x=>x.type==='table').rows;return `<p class="lead">Repérez ce que vous maîtrisez et ce que vous souhaitez reprendre.</p>${rows.slice(1).map((r,i)=>`<fieldset class="assessment"><legend>${e(r[0])}</legend><div>${['Oui','Partiellement','Non'].map((v,j)=>`<label><input type="radio" name="eval-${i}" value="${v}" data-save="eval-${i}" ${saved['eval-'+i]===v?'checked':''}>${v}</label>`).join('')}</div><label class="comment-label">Commentaire<input type="text" data-save="comment-${i}" value="${e(saved['comment-'+i]||'')}" placeholder="Ce que je veux revoir…"></label></fieldset>`).join('')}${exportButton()}`}
function classify(){const list=['challenge-100j-mon-dossier/','fiche-depart-candidat.md','un brouillon non relu','un document relu et classé','un fichier conservé dans le portfolio'];return `<div class="exercise"><h3>À vous de classer</h3>${list.map((v,i)=>`<label>${e(v)}<select data-classify="${i}" aria-label="Classer ${e(v)}"><option value="">Choisir…</option>${['Dossier','Fichier','Trace','Livrable','Preuve'].map(v=>`<option>${v}</option>`).join('')}</select></label>`).join('')}<button class="secondary" id="check-classify">Vérifier mes réponses</button><p id="classify-feedback" role="status"></p></div>`}
function renderItems(items){let model=0;let html='';let skipChecklist=false;for(const x of items){if(x.text==='Checklist avant la séance 02'){skipChecklist=true;html+=checks();continue}if(skipChecklist&&x.type==='li')continue;if(x.type==='h3')html+=`<h3>${e(x.text)}</h3>`;else if(x.type==='p'){if(!/^\.+$/.test(x.text))html+=`<p>${e(x.text)}</p>`}else if(x.type==='li')html+=`<p class="bullet">${e(x.text)}</p>`;else if(x.type==='table'){if(x.rows[0][0]==='Élément'&&x.rows[0][1]==='Votre réponse')html+=classify();else html+=table(x.rows)}else if(x.type==='copy')html+=copyBlock(x.text,x.label,x.text.startsWith('# ')?fileNames[model++]:'prompt.md');else if(x.type==='code')html+=`<pre class="tree">${e(x.text)}</pre>`;else if(x.type==='note'){const [title,...rest]=x.text.split('\n');html+=`<article class="note"><h3>${e(title)}</h3>${rest.map(t=>`<p>${e(t)}</p>`).join('')}</article>`}}return html;}
function lesson(){const n=state.section;let html=n===0?intro():`<section class="lesson"><p class="eyebrow">MODULE 01 / ÉTAPE ${String(n).padStart(2,'0')}</p><h1>${e(data.sections[n-1].title)}</h1>${n===7?reflection():n===9?assessment():renderItems(data.sections[n-1].items)}</section>`;html+=`<nav class="page-nav" aria-label="Navigation dans la leçon">${n>0?`<a href="#lesson/${n-1}">← ${titles[n-1]}</a>`:'<span></span>'}<span>${n+1} / ${titles.length}</span>${n<titles.length-1?`<a href="#lesson/${n+1}">${titles[n+1]} →</a>`:'<a href="#prompts">Ouvrir les prompts →</a>'}</nav>`;return html;}
const slides=[
 ['OUVERTURE','Apprendre à produire<br>avec l’IA.',`<p class="slide-lead">Challenge 100 jours · Relance automne 2026</p><div class="slide-rule">Vendredi 25 septembre 2026 · 19 h · Heure du Maroc</div><p>Module 01 — Cadrage et prise de conscience</p><p class="speaker">Prof. Abderrahman EL HISSE</p>`],
 ['LE CAP','Une première preuve.<br>Pas seulement des notes.',`<p class="slide-lead">À la fin de cette séance, vous aurez clarifié votre objectif et créé votre fiche de départ.</p><div class="file-display">fiche-depart-candidat.md</div><p>Un fichier simple, relu, daté et classé.</p>`],
 ['DEUX AXES','Un outil.<br>Une méthode.',`<div class="slide-columns"><article><span>01</span><h2>VS Code</h2><p>Créer un dossier<br>Créer un fichier<br>Écrire et enregistrer</p></article><article><span>02</span><h2>LN-IA</h2><p>Vision<br>Méthode<br>Impact et preuves</p></article></div>`],
 ['DÉROULEMENT','Le programme de la séance',`<ol class="agenda">${['Accueil et cadrage','Pourquoi le Challenge 100 jours ?','Découvrir VS Code et créer un fichier','Vision, méthode et impact LN-IA','Intention et engagement','Premier livrable','Questions-réponses','Consignes après séance'].map(x=>`<li>${x}</li>`).join('')}</ol>`],
 ['LES MOTS UTILES','Du dossier à la preuve',`<div class="slide-terms"><p><b>Dossier</b><span>Un espace pour organiser.</span></p><p><b>Fichier</b><span>Un contenu que l’on enregistre.</span></p><p><b>Trace</b><span>Un premier signe de travail.</span></p><p><b>Livrable</b><span>Une production utile et présentable.</span></p><p><b>Preuve</b><span>Un livrable qui montre une progression.</span></p></div>`],
 ['LA MÉTHODE','Produire, puis vérifier.',`<div class="cycle">${['Intention','Prompt','Production','Contrôle humain','Correction','Classement','Preuve'].map((x,i)=>`<div><span>0${i+1}</span>${x}</div>`).join('')}</div><p>Quel livrable dois-je obtenir ? Comment vérifier sa qualité ?</p>`],
 ['DÉMONSTRATION','Ouvrir son atelier',`<ol class="big-list"><li>Créer <code>challenge-100j-mon-dossier</code>.</li><li>L’ouvrir dans VS Code.</li><li>Créer le dossier <code>01-depart</code>.</li><li>Créer <code>fiche-depart-candidat.md</code>.</li><li>Écrire, puis enregistrer avec Ctrl+S.</li></ol>`],
 ['À VOUS','Rédigez votre intention.',`<p class="slide-lead">Écrivez trois phrases simples.</p><ol class="big-list"><li>Mon activité actuelle est…</li><li>Je veux apprendre à produire…</li><li>Ma première preuve utile sera…</li></ol><p>Développez ensuite un paragraphe de 5 à 7 lignes.</p>`],
 ['LE PROMPT','Demander avec précision',`<blockquote>Aide-moi à clarifier mon objectif personnel en 10 lignes maximum.</blockquote><p class="slide-lead">Précisez votre activité, la production souhaitée et votre difficulté principale.</p><a class="secondary" href="#prompts">Ouvrir les prompts à copier →</a>`],
 ['LE PREMIER LIVRABLE','Compléter la fiche de départ',`<div class="slide-columns"><article><h2>Votre contexte</h2><p>Nom et prénom<br>Activité actuelle<br>Pourquoi ce Challenge ?</p></article><article><h2>Votre objectif</h2><p>Premier livrable<br>Difficulté à dépasser<br>Preuve attendue</p></article></div><p>Relisez. Corrigez. Datez. Conservez une copie dans votre portfolio.</p>`],
 ['AVANT LA SÉANCE 02','Trois fichiers pour avancer',`<ol class="big-list"><li><code>fiche-depart-candidat.md</code></li><li><code>objectif-personnel-challenge.md</code></li><li><code>liste-premiers-livrables.md</code></li></ol><p class="slide-lead">Classez les deux premiers dans 01-depart et la liste dans 03-livrables. Conservez vos preuves dans 04-portfolio-preuves.</p>`],
 ['POUR CONTINUER','Le livrable prouve.',`<div class="manifesto"><p>L’IA <em>propose.</em></p><p>L’humain <em>contrôle.</em></p><p>L’atelier <em>organise.</em></p><p>Le livrable <em>prouve.</em></p></div><p>Vos questions, vos difficultés, votre première action.</p>`]
];
function presentation(){const [tag,title,body]=slides[state.slide];return `<section class="presentation"><div class="slide"><div class="slide-top"><span class="eyebrow">SÉANCE 01 / ${tag}</span><img src="${asset('logo-ln-ia.png')}" alt="LN-IA"></div><h1>${title}</h1>${body}</div><nav class="slide-controls" aria-label="Navigation présentation"><button id="prevslide" ${state.slide===0?'disabled':''}>← Précédent</button><span>${String(state.slide+1).padStart(2,'0')} <small>/ ${slides.length}</small></span><button id="nextslide" ${state.slide===slides.length-1?'disabled':''}>Suivant →</button></nav><p class="slide-help">Flèches ← → pour avancer · F pour le plein écran · Échap pour revenir à la leçon</p></section>`;}
function prompts(){return `<section class="lesson"><p class="eyebrow">L’ATELIER / COPIER, ADAPTER, VÉRIFIER</p><h1>Les mots pour<br>passer à l’action.</h1><p class="lead">Copiez un prompt, complétez votre contexte, puis collez-le dans votre outil IA. Relisez chaque réponse avant de la conserver.</p>${data.prompts.map((p,i)=>`<h2>${String(i+1).padStart(2,'0')} · ${promptNames[i]}</h2>${copyBlock(p,promptNames[i],`prompt-${i+1}.md`)}`).join('')}<h2>Vos trois modèles de fichiers</h2><p>À copier dans VS Code ou à télécharger directement.</p>${data.models.map((m,i)=>copyBlock(m,fileNames[i],fileNames[i])).join('')}</section>`}
function gallery(){return `<section class="lesson"><p class="eyebrow">SUPPORTS VISUELS / AUTOMNE 2026</p><h1>Les affiches<br>de la séance.</h1><p class="lead">Ouvrez un visuel pour le présenter ou téléchargez-le pour le partager.</p><div class="poster-grid">${posters.map(([f,t],i)=>`<article><button class="poster-open" data-poster="${i}" aria-label="Agrandir ${t}"><img src="${asset(f)}" alt="${t} — séance 01 LN-IA, 25 septembre 2026" loading="lazy"></button><h2>${t}</h2><a download="${f}" href="${asset(f)}">Télécharger l’affiche ↓</a></article>`).join('')}</div></section>`}
function render(){blocks.length=0;document.body.classList.toggle('presenting',state.view==='slides');document.querySelectorAll('[data-view]').forEach(a=>{a.classList.toggle('active',a.dataset.view===state.view);a.setAttribute('aria-current',a.dataset.view===state.view?'page':'false')});document.querySelectorAll('[data-section]').forEach(a=>{const on=state.view==='lesson'&&+a.dataset.section===state.section;a.classList.toggle('active',on);a.setAttribute('aria-current',on?'step':'false')});document.getElementById('main').innerHTML=state.view==='lesson'?lesson():state.view==='slides'?presentation():state.view==='prompts'?prompts():gallery();wire();}
function goSlide(delta){location.hash=`slides/${Math.max(0,Math.min(slides.length-1,state.slide+delta))}`}
function wire(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(blocks[+b.dataset.copy],b));document.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>download(blocks[+b.dataset.download],b.dataset.name));document.querySelectorAll('[data-save]').forEach(el=>el.addEventListener('input',()=>{saved[el.dataset.save]=el.type==='checkbox'?el.checked:el.value;persist()}));document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{let s='# Mon travail — Séance 01 LN-IA\n\nDate de séance : 25 septembre 2026\n\n';data.sections[6].items.filter(x=>x.type==='p'&&x.text.startsWith('Question')).forEach((q,i)=>s+=`## ${q.text}\n\n${saved['ref-'+i]||'[À compléter]'}\n\n`);s+='## Checklist\n\n';checkItems.forEach((q,i)=>s+=`- [${saved['check-'+i]?'x':' '}] ${q}\n`);s+='\n## Auto-évaluation\n\n';data.sections[8].items.find(x=>x.type==='table').rows.slice(1).forEach((r,i)=>s+=`- ${r[0]} : ${saved['eval-'+i]||'Non renseigné'}\n  ${saved['comment-'+i]||''}\n`);download(s,'bilan-seance-01.md');notify('Votre bilan est téléchargé.')});document.querySelectorAll('[data-poster]').forEach(b=>b.onclick=()=>{const [f,t]=posters[+b.dataset.poster];const d=document.getElementById('lightbox');d.querySelector('img').src=asset(f);d.querySelector('img').alt=t;d.showModal()});const prev=document.getElementById('prevslide');if(prev)prev.onclick=()=>goSlide(-1);const next=document.getElementById('nextslide');if(next)next.onclick=()=>goSlide(1);const ck=document.getElementById('check-classify');if(ck)ck.onclick=()=>{const ans=['Dossier','Fichier','Trace','Livrable','Preuve'];let ok=0;document.querySelectorAll('[data-classify]').forEach(s=>{let valid=s.value===ans[+s.dataset.classify]||(+s.dataset.classify===3&&s.value==='Preuve');s.classList.toggle('correct',valid);s.classList.toggle('incorrect',!valid);if(valid)ok++});document.getElementById('classify-feedback').textContent=`${ok}/5 réponses pertinentes. Dossier → Fichier → Trace → Livrable → Preuve. Un document relu et classé devient aussi une preuve lorsqu’il montre votre progression.`};}
function route(){const [v,id]=location.hash.slice(1).split('/');state.view=['lesson','slides','prompts','posters'].includes(v)?v:'lesson';if(state.view==='lesson')state.section=Math.max(0,Math.min(titles.length-1,Number(id)||0));if(state.view==='slides')state.slide=Math.max(0,Math.min(slides.length-1,Number(id)||0));render();window.scrollTo(0,0);document.body.classList.remove('menu-open');document.getElementById('menu').setAttribute('aria-expanded','false');document.title=`${state.view==='lesson'?titles[state.section]:state.view==='slides'?'Présentation':state.view==='prompts'?'Prompts':'Affiches'} · Séance 01 LN-IA`;}
shell();route();window.addEventListener('hashchange',route);document.addEventListener('keydown',ev=>{if(/INPUT|TEXTAREA|SELECT/.test(ev.target.tagName)||document.querySelector('dialog[open]'))return;if(state.view==='slides'){if(['ArrowRight','PageDown',' '].includes(ev.key)){ev.preventDefault();goSlide(1)}if(['ArrowLeft','PageUp'].includes(ev.key)){ev.preventDefault();goSlide(-1)}if(ev.key==='Escape')location.hash='lesson/0';if(ev.key.toLowerCase()==='f')document.getElementById('fullscreen').click();}});
